-- ============================================================
-- 1. CREATE TABLE
-- ============================================================
create table if not exists tours (
  id            integer primary key,
  name          text not null,
  image         text,
  location      text,
  duration      text,
  activity      text,
  difficulty    text,
  price         numeric,
  price_label   text,
  category      text,
  tag           text,
  tag_color     text,
  color         text,
  description    text,
  highlights    text[],
  included      text[],
  not_included  text[],
  long_desc     text
);

-- Enable public read access (no login required)
alter table tours enable row level security;
create policy "Public read" on tours for select using (true);

-- ============================================================
-- 2. INSERT ALL 34 TOURS
-- ============================================================
insert into tours values
(1,'Bosnian Castles – Guardians of History','/images/castle.jpg','Various, BiH','5 days / 4 nights','Walking','Easy',null,'Contact for pricing','History','Multi-day','#8b4513','#f8f0e8','Journey through Bosnia''s majestic medieval past. Visit royal seats, fortified towns, and ancient castles — from Bobovac to Jajce, Travnik, Vranduk, and beyond.',ARRAY['Bobovac Royal Fortress','Jajce Fortress & Waterfall','Vranduk above Bosna River','Srebrenik Medieval Fortress'],ARRAY['Transport Sarajevo–castle sites–Sarajevo','4 nights accommodation','Licensed guide throughout','Entry fees to all castles','Daily breakfast and two lunches'],ARRAY['Personal expenses','Travel insurance','Drinks'],'Journey through Bosnia''s majestic medieval past on the Bosnian Castles tour. Over five days, visit royal seats, fortified towns, and ancient castles that have stood the test of time — from the regal Bobovac to the mighty fortresses of Jajce, Travnik, Vranduk, and beyond.'),
(2,'Zelengora – The Emerald Jewel','/images/zelengora.jpg','Sutjeska NP, BiH','Full day','Walking','Medium',null,'Contact for pricing','Nature','Nature','#2d6a4f','#e8f4f0','Discover the untouched beauty of Zelengora mountain — clear lakes, verdant forests, and diverse wildlife in the heart of Sutjeska National Park.',ARRAY['Orlovačko Lake','Sutjeska National Park','Alpine wildlife','Pristine forests'],ARRAY['Transport Sarajevo–Zelengora–Sarajevo','Licensed mountain guide','Picnic lunch','Tour organisation'],ARRAY['Personal expenses','Travel insurance'],'Discover the untouched beauty of Zelengora, a mountain paradise renowned for its clear lakes, verdant forests, and diverse wildlife. This hike takes you through peaceful landscapes where nature reigns supreme — perfect for those wanting to escape the bustle and immerse themselves in Bosnia''s wild heart.'),
(3,'Bosansko Kolo – Dance of the Heart','/images/kolo.webp','Sarajevo, BiH','2–3 hours','Exploring','Easy',null,'Contact for pricing','Culture','Culture','#9b2335','#f8ebe8','Feel the rhythm of Bosansko Kolo, the traditional Bosnian circle dance. A joyful workshop celebrating one of the country''s most cherished cultural traditions.',ARRAY['Professional dance instructors','Cultural history presentation','Group dance participation','Local community experience'],ARRAY['Dance instruction by professional teachers','Cultural background presentation','Social dance opportunity','Tour organisation'],ARRAY['Transport','Personal expenses'],'Feel the rhythm and connection of Bosansko Kolo, a traditional circle dance that brings people together across Bosnia. Whether you''re a beginner or a seasoned dancer, this workshop offers a joyful introduction to one of the country''s most cherished cultural traditions.'),
(4,'Sarajevo Through Museums','/images/museums.jfif','Sarajevo, BiH','3–4 hours','Walking','Easy',null,'Contact for pricing','History','History','#8b4513','#f8f0e8','Walk through Sarajevo''s most important museums — from Ottoman and Austro-Hungarian periods to the Siege of the 1990s. A journey through time.',ARRAY['Museum of Sarajevo 1878–1918','War Childhood Museum','Tunnel of Hope Museum','Licensed guide'],ARRAY['Entrance fees','Licensed guide','Optional coffee break'],ARRAY['Transport','Personal expenses'],'Experience Sarajevo''s complex and layered history by walking through its most important museums. A journey through time — from the Ottoman and Austro-Hungarian periods, through the assassination of Franz Ferdinand, to the Siege of Sarajevo in the 1990s.'),
(5,'Hajdučka vrata – Gateway to Wilderness','/images/hajducka-vrata.jpg','Bosnia, BiH','Full day','Walking','Medium',null,'Contact for pricing','Nature','Adventure','#2d6a4f','#e8f4f0','Hike through forests and rocky terrain to the stunning natural rock formation of Hajdučka vrata. Breathtaking panoramas and rich folklore of the mountain rebels.',ARRAY['Natural rock gate formation','Dense forest trails','Hajduk folklore & legends','Panoramic mountain views'],ARRAY['Transport Sarajevo–Hajdučka vrata–Sarajevo','Licensed mountain guide','Picnic lunch','Tour organisation'],ARRAY['Personal expenses','Travel insurance'],'Step through Hajdučka vrata and enter a world of natural wonders and rich history. This unique rock formation has inspired countless tales of hajduks, the mountain rebels of the Balkans. Hike scenic trails that weave through forests and rocky terrain, enjoy breathtaking panoramas, and connect with the spirit of Bosnia''s wild mountains.'),
(6,'Visočica Wild Paths','/images/visocica.jpg','Visočica, BiH','6–8 hours','Exploring','Medium',null,'Contact for pricing','Nature','Hiking','#4a7c1f','#f0f8e8','Hike along shepherd trails across open plateaus with dramatic views of the Dinaric Alps. Ancient stećak tombstones, wild horses, and eagles await.',ARRAY['Shepherd trails','Ancient stećak tombstones','Wild horses & eagles','Dinaric Alps panorama'],ARRAY['Professional mountain guide','Transport','Picnic-style lunch'],ARRAY['Personal expenses','Travel insurance'],'Welcome to Visočica, one of Bosnia''s most captivating and untouched mountain ranges — where wild beauty, silence, and panoramic ridges create a true hiker''s paradise. Hike along shepherd trails, across open plateaus, and up to dramatic viewpoints where the Dinaric Alps unfold before your eyes.'),
(7,'Lakes of Treskavica Dream','/images/treskavica.jpg','Treskavica, BiH','7–9 hours','Exploring','Medium',null,'Contact for pricing','Nature','Nature','#1a6b9a','#e8f0f8','Enter the dreamlike world of Treskavica — glacial lakes, wildflower meadows, and limestone peaks. Visit Veliko Jezero, Malo Jezero, and Platno lake.',ARRAY['Veliko & Malo Jezero','Platno glacial lake','Wildflower meadows','Limestone peaks'],ARRAY['Licensed mountain guide','Transport','Packed lunch'],ARRAY['Personal expenses','Travel insurance'],'Enter the dreamlike world of Treskavica, one of the most beautiful and underrated mountains in Bosnia. Known for its crystal-clear glacial lakes, wildflower meadows, and dramatic limestone peaks, this hiking tour offers a magical escape into pristine nature.'),
(8,'Skakavac Falls Hike','/images/skakavac.webp','Nahorevo, BiH','4–5 hours','Exploring','Medium',null,'Contact for pricing','Nature','Nature','#2d6a4f','#e8f4f0','Hike through pine forests to the thundering Skakavac waterfall. Breathtaking panoramas from above, then descend to feel the refreshing mist at the base.',ARRAY['Skakavac Waterfall','Pine forest trails','Panoramic viewpoints','Picnic lunch in nature'],ARRAY['Transport Sarajevo–Nahorevo–Sarajevo','Licensed mountain guide','Picnic lunch','Tour organisation'],ARRAY['Personal expenses','Travel insurance'],'This guided hike leads you through fragrant pine forests, wildflower-covered meadows, and scenic viewpoints before revealing the thundering curtain of water at Skakavac. Enjoy breathtaking panoramas from above, then descend to feel the refreshing mist at the base of the falls.'),
(9,'Maglić & Trnovačko Lake – Peaks and Reflections','/images/maglic.jpg','Sutjeska NP, BiH','Full day','Walking','Medium',null,'Contact for pricing','Nature','Epic','#5b3ab5','#ece8f8','Hike to Maglić, the highest peak in BiH, and the stunning heart-shaped Trnovačko Lake with emerald waters and Dinaric Alps panoramas.',ARRAY['Maglić Peak 2386m','Trnovačko heart-shaped lake','Dinaric Alps views','Alpine environment'],ARRAY['Transport Sarajevo–Maglić–Sarajevo','Licensed mountain guide','Picnic lunch','Tour organisation'],ARRAY['Personal expenses','Travel insurance'],'Experience the breathtaking landscapes of Maglić & Trnovačko Lake, where soaring mountain peaks meet crystal-clear alpine lakes. This demanding yet rewarding hike offers spectacular views and the chance to connect deeply with Bosnia''s wild mountain heart.'),
(10,'Prenj – Peaks and Trails','/images/prenj.jpg','Prenj Mountain, BiH','Full day','Walking','Medium',null,'Contact for pricing','Nature','Hiking','#4a7c1f','#f0f8e8','Trek through rugged Prenj Mountain — dramatic peaks, alpine meadows, and crystal-clear streams with spectacular views of the Dinaric Alps.',ARRAY['Dramatic mountain peaks','Alpine meadows','Mountain huts','Local flora & fauna'],ARRAY['Transport Sarajevo–Prenj–Sarajevo','Licensed mountain guide','Picnic lunch','Tour organisation'],ARRAY['Personal expenses','Travel insurance'],'Discover the wild beauty of Prenj Mountain, a paradise for hikers and nature lovers. With soaring summits, lush meadows, and crystal-clear streams, Prenj offers some of the most breathtaking alpine scenery in Bosnia.'),
(11,'Herzegovina – Heart of the South','/images/herzegovina.jpg','Mostar, BiH','3 days / 2 nights','Exploring','Easy',null,'Contact for pricing','History','Multi-day','#c25b1a','#f8f0e8','Explore the soul of southern Bosnia — Mostar Old Town, Blagaj Tekke, Počitelj fortress, Kravice Waterfalls, and Herzegovinian wine tasting.',ARRAY['UNESCO Stari Most','Blagaj Tekke','Kravice Waterfalls','Wine tasting'],ARRAY['Transport Sarajevo–Herzegovina–Sarajevo','2 nights accommodation in Mostar','Licensed guide','Entry fees','Breakfast and one lunch','Wine tasting'],ARRAY['Personal expenses','Travel insurance','Additional meals'],'Dive into the soul of southern Bosnia — wander through iconic towns steeped in history, discover sacred sites, and refresh yourself beneath magnificent waterfalls. Savor local wines and experience the warm hospitality of Herzegovina''s villages.'),
(12,'Kayak Trebižat – Flowing Serenity','/images/kayak.jpg','Trebižat River, BiH','Full day','Exploring','Easy',null,'Contact for pricing','Nature','Water','#1a6b9a','#e8f0f8','Paddle through calm turquoise waters of the Trebižat River, discover hidden waterfalls, and enjoy peaceful moments in Herzegovina''s most beautiful natural setting.',ARRAY['Turquoise river kayaking','Krupa Waterfalls','Traditional village visits','Riverside lunch'],ARRAY['Transport to and from kayaking site','Professional kayak guide & safety equipment','Full-day kayaking','Lunch and refreshments','Tour organisation'],ARRAY['Personal expenses','Travel insurance'],'Immerse yourself in a full-day kayaking adventure on the Trebižat River. Paddle through calm turquoise waters, discover hidden waterfalls, and enjoy peaceful moments in one of Herzegovina''s most beautiful natural settings.'),
(13,'Shepherds – Life in the Highlands','/images/shepherds.jpg','Mountain Highlands, BiH','Half day','Walking','Easy',null,'Contact for pricing','Culture','Culture','#9b2335','#f8ebe8','Visit remote mountain pastures and meet local shepherd families. Taste homemade cheeses, experience centuries-old traditions, and connect with Bosnia''s pastoral heritage.',ARRAY['Highland shepherd families','Homemade cheese tasting','Traditional rustic huts','Mountain pastures'],ARRAY['Transport from Sarajevo to highland pastures','Licensed local guide','Tasting of traditional dairy products','Tour organisation'],ARRAY['Personal expenses','Travel insurance'],'Discover the timeless traditions of Bosnian shepherds. Wander mountain meadows, meet local families, and savour authentic cheeses made from fresh alpine milk. This cultural journey connects you with Bosnia''s pastoral heritage.'),
(14,'Taste Sarajevo','/images/taste-sarajevo.jpg','Sarajevo, BiH','3–4 hours','Exploring','Easy',29,'29 € / person','Culture','Gastro','#c23a1a','#f8ebe8','A flavorful journey through Sarajevo''s culinary heritage — ćevapi, baklava, Bosnian coffee, vibrant local markets, and traditional eateries.',ARRAY['5+ tastings','Bosnian coffee ritual','Local market tour','Hidden food spots'],ARRAY['5+ tastings (savoury and sweet)','Bosnian coffee experience','Guide','Local stories'],ARRAY['Transport','Additional food & drinks'],'Embark on a flavorful journey through Sarajevo''s rich culinary heritage. This tour blends history, culture, and unforgettable tastes — from the smoky aroma of ćevapi to the delicate sweetness of baklava, and the unique ritual of Bosnian coffee.'),
(15,'Traces of the Olympics','/images/olympics.avif','Sarajevo, BiH','4–5 hours','Exploring','Medium',39,'39 € / person','History','History','#8b4513','#f8f0e8','Relive the glory of the 1984 Winter Olympics — the bobsled track on Trebević, Ski Jump at Igman, and Olympic infrastructure now standing as symbols of time.',ARRAY['Olympic bobsled track','Ski Jump at Igman','Optional cable car ride','Olympic history'],ARRAY['Transport','Licensed guide','Olympic sites','Optional cable car ride'],ARRAY['Personal expenses','Cable car (optional extra)'],'Relive the glory of the 1984 Winter Olympics as you explore iconic venues on the mountains of Sarajevo — the Olympic bobsled track on Trebević, the Ski Jump at Igman, and remnants of infrastructure that once welcomed the world.'),
(16,'Herzegovina in One Breath','/images/herzegovina1.webp','Herzegovina, BiH','10–12 hours','Exploring','Easy',59,'59 € / person','Nature','Popular','#2d6a4f','#e8f4f0','Mostar Old Bridge, Blagaj Tekke, Počitelj fortress, and Kravice Waterfalls — the soul of Herzegovina in one unforgettable day.',ARRAY['Stari Most Mostar','Blagaj Dervish Tekke','Počitelj medieval village','Kravice Waterfalls'],ARRAY['Transport Sarajevo–Herzegovina–Sarajevo','Licensed guide','Entry fees','Lunch','Tour organisation'],ARRAY['Personal expenses','Travel insurance'],'Experience the soul of Herzegovina in a single unforgettable day. From emerald rivers to centuries-old stone towns, this journey blends history, culture, and nature — Mostar, Blagaj, Počitelj, and Kravice Waterfalls all in one day.'),
(17,'Srebrenica – Memory and Reflection','/images/srebrenica.jpg','Srebrenica, BiH','Full day','Exploring','Easy',69,'69 € / person','History','Memorial','#555555','#f0f0f0','A deeply moving journey to the Srebrenica Memorial Center in Potočari — honouring the victims of 1995 and carrying a message of peace and remembrance.',ARRAY['Memorial Cemetery Potočari','Former UN base','Museum & survivor testimonies','Guided historical narrative'],ARRAY['Transport Sarajevo–Srebrenica–Sarajevo','Licensed guide','Entry to Memorial Center and museum','Tour organisation'],ARRAY['Personal expenses','Travel insurance'],'More than a tour — a journey into one of the most tragic chapters of modern European history. Guided with compassion and respect, this experience sheds light on the events of July 1995, offering a deeper understanding of the past and a message about the importance of peace and remembrance.'),
(18,'Travnik & Jajce – Royal Towns and Waterfalls','/images/travnik-jajce.jpg','Travnik / Jajce, BiH','Full day','Walking','Medium',69,'69 € / person','History','History','#8b4513','#f8f0e8','Ottoman-era Travnik and medieval Jajce — a spectacular city waterfall, fortress ruins, Pliva watermills, and authentic Bosnian flavors.',ARRAY['Travnik Fortress','Jajce city waterfall','Pliva Watermills','Travnička kava & cheese'],ARRAY['Transport Sarajevo–Travnik–Jajce–Sarajevo','Licensed guide','Entry fees to fortress and museums','Tour organisation'],ARRAY['Meals','Personal expenses','Travel insurance'],'Step into Bosnia''s royal past with this tour blending history, architecture, and breathtaking natural beauty. In Travnik, walk through streets once ruled by Ottoman governors. In Jajce, marvel at the rare sight of a waterfall in the heart of the city.'),
(19,'Visoko – Valley of the Bosnian Pyramids','/images/visoko.jpg','Visoko, BiH','Half day / Full day','Exploring','Easy',39,'39 € / person','Nature','Mystery','#5b3ab5','#ece8f8','Uncover the mystery of the Bosnian Pyramids — walk the slopes of the Pyramid of the Sun and explore the Ravne Tunnels underground network.',ARRAY['Pyramid of the Sun','Ravne Tunnels','Archaeological theories','Local crafts & snacks'],ARRAY['Transport Sarajevo–Visoko–Sarajevo','Licensed guide','Entry to Ravne Tunnels and Pyramid sites','Tour organisation'],ARRAY['Personal expenses','Travel insurance'],'Uncover one of Bosnia''s most intriguing mysteries — the Bosnian Pyramids. Walk the slopes of the Pyramid of the Sun, explore the Ravne Tunnels underground network, and immerse yourself in a story that blends archaeology, history, and legend.'),
(20,'Prokoško Lake – Alpine Serenity','/images/prokoshko-lake.jpg','Vranica Mountain, BiH','Full day','Walking','Medium',69,'69 € / person','Nature','Nature','#2d6a4f','#e8f4f0','A glacial lake on Vranica Mountain surrounded by alpine meadows and shepherd huts — serenity, fresh mountain air, and traditional highland cuisine.',ARRAY['Prokoško glacial lake','Alpine meadows','Shepherd community','Traditional mountain lunch'],ARRAY['Transport Sarajevo–Prokoško Lake–Sarajevo','Licensed mountain guide','Traditional mountain lunch','Tour organisation'],ARRAY['Personal expenses','Travel insurance'],'Escape to the tranquil beauty of Prokoško Lake, a hidden gem in the heart of Bosnia''s mountains. Surrounded by crystal-clear waters and alpine pastures, this glacial lake offers a perfect blend of nature and tradition.'),
(21,'Foča & Tjentište – Nature and History in the Sutjeska Valley','/images/foca-tjentiste.jpg','Foča / Sutjeska, BiH','Full day','Walking','Easy',49,'49 € / person','History','History','#8b4513','#f8f0e8','Sutjeska National Park, the WWII Battle memorial, Foča''s Ottoman heritage, and pristine mountain rivers — nature and history intertwined.',ARRAY['Memorial Wall Tjentište','Valley of Heroes','Foča Ottoman heritage','Sutjeska forest trails'],ARRAY['Transport Sarajevo–Foča–Tjentište–Sarajevo','Licensed guide','Entry to memorial sites','Tour organisation'],ARRAY['Meals','Personal expenses','Travel insurance'],'Step into the heart of Bosnia''s wilderness and history. Wander the trails of Sutjeska National Park, visit monumental memorials dedicated to bravery during WWII, and discover Foča''s Ottoman charm.'),
(22,'Višegrad – Bridge Over the Drina','/images/visegrad.jpg','Višegrad, BiH','Half day','Walking','Easy',59,'59 € / person','History','UNESCO','#c25b1a','#f8f0e8','The iconic UNESCO-listed Mehmed Paša Sokolović Bridge, immortalized by Nobel laureate Ivo Andrić, and the cultural complex of Andrićgrad.',ARRAY['UNESCO Sokolović Bridge','Andrićgrad complex','Drina River views','Ottoman architecture'],ARRAY['Transport Sarajevo–Višegrad–Sarajevo','Licensed guide','Entry to Andrićgrad (optional)','Tour organisation'],ARRAY['Personal expenses','Travel insurance'],'Discover the beauty and history of Višegrad, where the iconic Ottoman-era bridge stands as a symbol of cultural heritage and literary fame. Walk the stone arches, enjoy the serene river views, and explore Andrićgrad.'),
(23,'Medjugorje – Place of Peace and Prayer','/images/medjugorje.jpg','Medjugorje, BiH','Full day','Walking','Easy',59,'59 € / person','Culture','Spiritual','#1a6b9a','#e8f0f8','One of the world''s most visited pilgrimage sites — Church of St. James, Apparition Hill, and an atmosphere of deep peace and quiet contemplation.',ARRAY['Church of St. James','Apparition Hill walk','Personal reflection time','Spiritual atmosphere'],ARRAY['Transport Sarajevo–Medjugorje–Sarajevo','Licensed guide','Tour organisation'],ARRAY['Personal expenses','Travel insurance','Meals'],'Find tranquility and inspiration at Medjugorje, one of the world''s most visited pilgrimage sites. Whether you are a pilgrim or a traveler, Medjugorje offers an atmosphere of deep peace and quiet contemplation.'),
(24,'Rafting on the Tara River','/images/rafting-tara.jpg','Tara River, Montenegro','Half day / Full day','Exploring','Easy',99,'99 € / person','Nature','Adrenaline','#1a6b9a','#e8f0f8','Navigate the "Tear of Europe" — crystal-clear Tara River through Europe''s deepest canyon, surrounded by towering cliffs and lush forests.',ARRAY['Europe''s deepest canyon','Crystal-clear waters','All skill levels','Professional safety gear'],ARRAY['Transport to and from rafting site','Professional rafting guide & safety gear','Briefing and instructions','Tour organisation'],ARRAY['Personal expenses','Travel insurance','Meals'],'Dive into adventure with rafting on the Tara River, a thrilling journey through one of Europe''s most spectacular river canyons. Navigate crystal-clear waters surrounded by towering cliffs and lush forests — the "Tear of Europe".'),
(25,'Rafting on the Neretva River','/images/rafting-neretva.jpg','Neretva River, BiH','Half day / Full day','Exploring','Easy',60,'60 € / person','Nature','Water','#2d6a4f','#e8f4f0','Paddle through emerald Neretva waters framed by steep canyon walls — gentle stretches and thrilling rapids perfect for all skill levels.',ARRAY['Emerald canyon waters','Exciting rapids','Family friendly','Professional guide & gear'],ARRAY['Transport to and from rafting site','Professional rafting guide & safety equipment','Safety briefing','Tour organisation'],ARRAY['Personal expenses','Travel insurance','Meals'],'Feel the rush of white-water excitement on the Neretva River — emerald waters framed by steep canyon walls. The river''s mix of gentle stretches and thrilling rapids makes it perfect for all skill levels.'),
(26,'Mystic Caves of Bijambare','/images/bijambare-caves.jpg','Bijambare, BiH','4–5 hours','Exploring','Easy',29,'29 € / person','Nature','Nature','#4a7c1f','#f0f8e8','Bosnia''s largest cave system tucked in a tranquil pine forest — spectacular stalactites, stalagmites, and shimmering underground halls.',ARRAY['Main cave tour','Stalactites & stalagmites','Pine forest walk','Picnic lunch'],ARRAY['Transport Sarajevo–Bijambare–Sarajevo','Licensed guide','Entry tickets to the caves','Picnic lunch'],ARRAY['Personal expenses','Travel insurance'],'Step into a world millions of years in the making at the Bijambare Caves, a natural wonder tucked away in a tranquil pine forest — Bosnia''s largest cave system, where spectacular stalactites and shimmering underground halls await.'),
(27,'Trebević: Forest Above the City','/images/trebevic.webp','Trebević, Sarajevo','3–4 hours','Exploring','Easy',29,'29 € / person','Nature','City Escape','#2d6a4f','#e8f4f0','Pine-scented forests, panoramic Sarajevo views, and the haunting 1984 Olympic bobsled track — nature, history, and memory on the city''s doorstep.',ARRAY['1984 Olympic bobsled track','Sarajevo panorama','Optional cable car','Forest hiking trails'],ARRAY['Optional cable car ride','Guide','Short break with a view'],ARRAY['Transport','Personal expenses','Cable car (optional)'],'Escape the city buzz and step into the green lungs of Sarajevo — Mount Trebević, where nature, history, and memory intertwine. Walk pine-scented forests, enjoy panoramic views of Sarajevo, and explore the haunting remains of the 1984 Olympic bobsled track.'),
(28,'Echoes of Sarajevo''s Jews','/images/jewish-heritage.jpg','Sarajevo, BiH','2–3 hours','Walking','Easy',19,'19 € / person','History','History','#8b4513','#f8f0e8','Discover Sarajevo''s Sephardic and Ashkenazi heritage — the Jewish Museum, Ashkenazi Synagogue, and one of the Balkans'' most significant Jewish cemeteries.',ARRAY['Old Jewish Temple / Museum','Ashkenazi Synagogue','Jewish Cemetery','Sephardic history since 1492'],ARRAY['Entrance fees','Licensed guide with historical expertise'],ARRAY['Transport','Personal expenses'],'Step into the rich and often overlooked world of Sarajevo''s Jewish community — one of the oldest in Europe. Learn how Sarajevo became a refuge for Jews expelled from Spain in the 15th century and discover stories of coexistence and survival.'),
(29,'Bobovac – Medieval Fortress of Kings','/images/bobovac.jpg','Bobovac, BiH','Half day','Exploring','Medium',49,'49 € / person','History','History','#8b4513','#f8f0e8','Walk paths once trodden by Bosnian kings at the royal fortress of Bobovac — stone walls, towers, and palaces with stunning countryside views.',ARRAY['Royal Bosnian fortress','Stone walls & towers','Forested hiking trail','Medieval kingdom history'],ARRAY['Transport Sarajevo–Bobovac–Sarajevo','Licensed guide','Entry fees','Tour organisation'],ARRAY['Personal expenses','Travel insurance'],'Step back in time at Bobovac, the royal fortress and capital of the medieval Bosnian Kingdom. Walk the paths once trodden by Bosnian kings, explore stone walls and towers with stunning countryside views.'),
(30,'War 1992–1995 Tour Sarajevo','/images/war-tour.jpg','Sarajevo, BiH','3–4 hours','Walking','Medium',29,'29 € / person','History','Memorial','#555555','#f0f0f0','The longest siege in modern history — visit the Tunnel of Hope, Sniper Alley, and destroyed neighborhoods. Personal stories of resilience, pain, and hope.',ARRAY['Tunnel of Hope Museum','Sniper Alley','Local guide & personal stories','City viewpoints'],ARRAY['Transport','Licensed local guide','Tunnel Museum visit','Optional city viewpoints'],ARRAY['Personal expenses','Travel insurance'],'Uncover the recent past of Sarajevo — a city that survived the longest siege in modern history. This deeply moving tour offers insight into the 1992–1995 war through real locations and preserved memory.'),
(31,'WWI – Assassination of Franz Ferdinand','/images/wwi-assassination.avif','Sarajevo, BiH','2–3 hours','Walking','Easy',15,'15 € / person','History','History','#8b4513','#f8f0e8','Walk the exact route of June 28, 1914 — the assassination that sparked WWI. Gavrilo Princip, the Young Bosnia movement, and the Museum of Sarajevo 1878–1918.',ARRAY['Assassination site Latin Bridge','Museum of Sarajevo 1878–1918','Young Bosnia movement','WWI historical narrative'],ARRAY['Visit to the assassination site','Museum of Sarajevo 1878–1918','Guided historical narrative'],ARRAY['Transport','Personal expenses'],'Step into the very streets where world history was changed forever. Walk the exact route of that fateful day in June 1914, learn about Gavrilo Princip and the Young Bosnia movement, and explore the political tension that turned Sarajevo into the centre of global attention.'),
(32,'Titov Bunker – Secret of Konjic','/images/titov-bunker.jpg','Konjic, BiH','Half day','Exploring','Easy',59,'59 € / person','History','Unique','#5b3ab5','#ece8f8','Built in total secrecy between 1953–1979, Tito''s nuclear bunker could sustain 350 people for 6 months. Cold War history meets contemporary art installations.',ARRAY['Cold War nuclear bunker','Secret corridors & command rooms','Contemporary art installations','Konjic Old Bridge'],ARRAY['Transport Sarajevo–Konjic–Sarajevo','Licensed guide','Entry to Titov Bunker','Tour organisation'],ARRAY['Personal expenses','Travel insurance'],'Step into one of the Cold War''s most astonishing secrets. Built in total secrecy between 1953 and 1979, this massive underground complex could sustain 350 people for up to six months. Today, it also serves as an art space — a unique meeting point of history and creativity.'),
(33,'Craft for Copper in Baščaršija Workshop','/images/craft-copper.jpg','Sarajevo, BiH','2–3 hours','Exploring','Easy',null,'Contact for pricing','Culture','Workshop','#c25b1a','#f8f0e8','Learn centuries-old copperworking techniques in the historic Baščaršija market. Shape, engrave, and polish your own copper souvenir to take home.',ARRAY['Hands-on copper crafting','Professional coppersmiths','Copper souvenir to keep','Baščaršija market setting'],ARRAY['Workshop materials and tools','Guidance from professional coppersmiths','Small copper souvenir','Tour organisation'],ARRAY['Transport','Personal expenses'],'Immerse yourself in Sarajevo''s rich artisan tradition at the Baščaršija market. Learn centuries-old copperworking techniques, shape and engrave your own unique keepsake, and take home a piece of authentic Bosnian craftsmanship.'),
(34,'Krajina (Una) – Wild Water and Wilderness','/images/krajina-una.jpg','Una River, BiH','3 days / 2 nights','Walking','Easy',null,'Contact for pricing','Nature','Multi-day','#1a6b9a','#e8f0f8','Raft through the wild Una River, hike along crystal-clear waterfalls, and unwind in eco-lodges surrounded by Bosnia''s most pristine natural region.',ARRAY['Una River rafting','Waterfalls & natural springs','Eco-lodge accommodation','Optional kayaking & swimming'],ARRAY['Transport Sarajevo–Una region–Sarajevo','2 nights accommodation','Licensed rafting guide & safety equipment','Entry to national park','Breakfast and one lunch'],ARRAY['Personal expenses','Travel insurance','Additional meals'],'Immerse yourself in the wild beauty of Krajina — paddle through stunning river canyons, hike along crystal-clear waterfalls, and unwind in comfortable eco-lodges surrounded by Bosnia''s most pristine natural region.')
on conflict (id) do nothing;
